name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  OUTPUT_PATH: ${{ github.workspace }}/docs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
      - uses: jetli/wasm-pack-action@v0.3.0
      - name: build
        run: wasm-pack build --target web --out-name wasm --out-dir ${{ env.OUTPUT_PATH }}
